cat/urls.py
from django.urls import path
from . import views

app_name = 'cat'
urlpatterns = [


    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),



    path('genre/<str:genre_name>/', views.genrepage, name='genre'),
    #path('', views.Home, name='홈'),
    path('<int:movieid>/', views.MovieDetail, name='영화상세'),
    #path('LnD', views.LnD_Page, name='영화호불호'),

]


config/urls.py
from django.contrib import admin
from django.urls import path, include

from cat import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myview/', include('cat.urls')),
    path('', views.index, name='index'),
]

cat/models.py
from django.db import models

# Create your models here.

cat/views.py
from django.shortcuts import render, redirect
from .form import UserForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from mc import *
from view import *
udb=UserDB()
mdb=MovieDB(udb)
rec=Recommender(udb,mdb)
entr=EntrancePage(udb)
# Create your views here.

def index(request):
    return HttpResponse("HI",request)

def genrepage(request, genre_name):
    #Fantasy Action Adventure Crime Thriller Animation Comedy Romance Children Drama Horror Mystery Sci-Fi  War Musical Documentary IMAX Western Film-Noir
    gpage = GenrePage(entr,mdb,udb,rec)
    gpage.getrecgenre(entr.getnow(),genre_name)
    movies = gpage.showrecgenre()
    username = entr.getnow()

    context = {
        'movies': movies,
        'genre_name': genre_name,
        'username': username,
    }
    return render(request, 'catflex/genrepage.html', context)

def login(request):
    #print(udb.ExtractUserList())
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            try:
                if entr.LogIn(form.cleaned_data.get('id')):
                    entr.LogIn(form.cleaned_data.get('id'))
                    #(udb.ExtractUserList())
                    return redirect('/myview/genre/Action/')
                else:
                    form = UserForm()
            except:
                pass
    else:
        form = UserForm()

    return render(request, 'catflex/login.html',{'form':form})


def logout(request):
    return HttpResponse(
        '''
        <p><h1>logout</h1></p>
        <a href="/myview/login/">
        login
        </a>
                '''
                )


def signup(request):
    """
    회원가입
    """

    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            entr.Register(form.cleaned_data.get('id'))
            #print(udb.ExtractUserList())
            login(request)
            return redirect('/myview/login/')
    else:
        form = UserForm()
    return render(request, 'catflex/signup.html', {'form': form})
'''
def Home (request):
    hmpage = homepage(entr, mdb, udb, rec)
    recmvlist=hmpage.SimilarRecommendmovies(entr.getnow())
    histroyrecommendlist=hmpage.HistoryRecommendation(entr.getnow())
    watchedlist=hmpage.HistoryList(entr.getnow())
    for items in recmvlist[:5]:
        recmvlist+=recmvlist[items]
        posterlist=list(posterlist.extend(hmpage.getmovieposter(items)))
        titlelist = list(titlelist.extend(hmpage.getmovietitle(items)))
        moviegenrelist = list(moviegenrelist.extend(hmpage.getmoviegenre(items)))
    for items in recommendmvsimiaritylist[:5]:
        simiaritylist=list(simiaritylist.extend(items))
    for items in histroyrecommendlist[:5]:
        hisrecmvlist=list(hisrecmvlist.extend(items))
        hisposterlist=list(hisposterlist.extend(hmpage.getmovieposter(items)))
        histitlelist = list(histitlelist.extend(hmpage.getmovietitle(items)))
        hismoviegenrelist = list(hismoviegenrelist.extend(hmpage.getmoviegenre(items)))
    for items in watchedlist[:5]:
        watchedrecmvlist=list(watchedrecmvlist.extend(items))
        watchedposterlist=list(watchedposterlist.extend(hmpage.getmovieposter(items)))
        watchedtitlelist = list(watchedtitlelist.extend(hmpage.getmovietitle(items)))
        watchedmoviegenrelist = list(watchedmoviegenrelist.extend(hmpage.getmoviegenre(items)))
    #리스트: for i in list[:꺼내고싶은 갯수 하면 갯수만큼 나옴]

    # 영화보여주고 아래에 유사도 표시를 한다고함

    context={'recmvlist':recmvlist,'posterlist':posterlist,'titlelist':titlelist,'moviegenrelist':moviegenrelist,
             'simiaritylist':simiaritylist,'hisrecmvlist':hisrecmvlist,'hisposterlist':hisposterlist,
             'histitlelist':histitlelist,'hismoviegenrelist':hismoviegenrelist,'watchedrecmvlist':watchedrecmvlist,
             'watchedposterlist':watchedposterlist,'watchedtitlelist':watchedtitlelist,
             'watchedmoviegenrelist':watchedmoviegenrelist}

    #로그인에서 로그인pk값으로 recommender 함수 돌아가게 해주는게 바람직함
    # SimSimliarRecommendation


    return render(request, "catfelx/홈.html", context)
'''
def MovieDetail(request, movieid):
    movie_id = movieid

    movie = {'title':mdb.GetTitle(movieid),'poster':mdb.GetPoster(movieid),'plot': mdb.GetPlot(movieid),'tag': mdb.GetTags(movie_id), 'release': mdb.GetRelease(movie_id), 'runtime': mdb.GetRuntime(movie_id) }
    context={
        'movie_id':movie_id, 'movie': movie, 'username': entr.getnow(),
    }

    return render(request, 'catflex/무비페이지.html', context)

def Like(request,movie_id):
    moviepage.thumbsup(entr.getnow(), movie_id)

def dislike(request,movie_id):
    moviepage.thumbsdown(entr.getnow(), movie_id)

def markwatched(request,movie_id):
    moviepage.WatchedMovie(entr.getnow(), movie_id)

templates/base.html
{% load static %}

<html lang="ko" xmlns="http://www.w3.org/1999/html">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>CATFLEX</title>
</head>
<body>
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 시작 -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용끝 -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/catflex/genrepage.html
{% extends 'base.html' %}
{% block content %}









<h1>{{ genre_name }}</h1>

<div class="row">

    {% for movie in movies %}
        <div class="col col-md-auto">
        <div class="card text-center border-dark mb-3 bg-light mb-3" style="width: 15rem;">
                <a href="{{ movie.url }}">
                    <img class="card-img-top" src="{{ movie.poster }}" width="200" height="260" alt="Card image cap">

                    <div class="card-header">
                                <h4 class="card-title">{{ movie.title }}</h4>
                        </div>
                </a>
        </div>
        </div>
    {% endfor %}

</div>






<!--
<div class="container my-3">
        <h1>{{ genre_name }}</h1>
        {% if movie_list %}
        <div class="category-group">
                {% for movie in movie_list %}
                        <div class="card" style="width: 15rem;">
                        <a href="https://oh16.notion.site/0603-2f23790a97ab4364b08edf3de958dfd4">
                                <img class="card-img-top" src="https://search.pstatic.net/sunny/?src=https%3A%2F%2Fimage.ohou.se%2Fi%2Fbucketplace-v2-development%2Fuploads%2Fproductions%2Fdescriptions%2Furl%2F163514095644161671.jpg&type=a340" alt="Card image cap">
                                <div class="card-body">
                                 <h5 class="card-title">{{ movie }}</h5>
                                </div>
                               </a>
                        </div>
                {% endfor %}
                </div>

        {% endif %}
</div>

<div class="container my-3">
        <h1>{{ genre_name }}</h1>
        {% if movie_list %}
                <div class="card" >
                {% for movie in movie_list %}
                        <a href="https://oh16.notion.site/0603-2f23790a97ab4364b08edf3de958dfd4">
                                {{ movie }}
                               <img src="https://search.pstatic.net/sunny/?src=https%3A%2F%2Fimage.ohou.se%2Fi%2Fbucketplace-v2-development%2Fuploads%2Fproductions%2Fdescriptions%2Furl%2F163514095644161671.jpg&type=a340"
                                      width=10%>
                        </a>
                {% endfor %}
                </div>
        {% endif %}
</div>
-->
{% endblock %}

templates/catflex/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                또는 <a href="{% url 'cat:signup' %}">계정을만드세요</a>
            </span>
        </div>
    </div>
    <form method="post" class="post-form" >
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/catflex/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'cat:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id">ID</label>
            <input type="text" class="form-control" name="id" id="id" value="{{ form.id.value|default_if_none:'' }}">
        </div>

        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/catflex/디자인.html
<h1 class="text-gray-500 text-xs tracking-widest title-font mb-1">Main page</h1>

<section class="text-gray-600 body-font" >
  <div class="container px-5 py-24 mx-auto" >
    <div class="flex flex-wrap -m-4" >
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full" >
        <a class="block relative h-48 rounded overflow-hidden" >
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
            <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >

        </a>
        <div class="mt-4" >
          <h2 class="text-gray-500 text-xs tracking-widest title-font mb-1" >Genre</h2>
        </div>

      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full" >
        <a class="block relative h-48 rounded overflow-hidden" >
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
 <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100">
             <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100">
        </a>
        <div class="mt-4">
          <h2 class="text-gray-500 text-xs tracking-widest title-font mb-1">watched movies</h2>


        </div>
      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full" >
        <a class="block relative h-48 rounded overflow-hidden" >
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100"  >
           <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
  <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" >
         <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100"  >
         <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100"  >

        </a>
        <div class="mt-4" >
          <h2 class="text-gray-500 text-xs tracking-widest title-font mb-1"  >similar movie</h2>
          <p class="mt-1" ></p>
        </div>

        </div>

    </div>
  </div>
</section>

templates/catflex/무비페이지.html


<div style="visibility: hidden;">visibility: hidden; 테스트</div>
{% extends 'base.html' %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden" >
  <div class="container px-5 py-24 mx-auto" >
    <div class="lg:w-4/5 mx-auto flex flex-wrap" >
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0" >
        <h2 class="text-sm title-font text-gray-500 tracking-widest" >MOVIE NAME</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ movie.title }}</h1>
        <div class="flex mb-4" >

        </div>
          <img src="{{ movie.poster }}" width="200" height="260">
        <p class="leading-relaxed mb-4" >{{ movie.plot }}
</p>
          <p></p>
          <p></p>
        <div class="flex border-t border-gray-200 py-2" >
          <span class="text-gray-500">Tags: </span>
          <span class="ml-auto text-gray-900" >{{ movie.tag }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2" >
          <span class="text-gray-500" >relrease: </span>
          <span class="ml-auto text-gray-900" >{{ movie.release }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2" >
          <span class="text-gray-500" >Runtime: </span>
          <span class="ml-auto text-gray-900" >{{ movie.runtime }}</span>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900" >좋아요</span>
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" >좋아요 표시 버튼입니다</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
        </div>
    </div>
  </div>
</section>

{% endblock %}

templates/catflex/홈.html
<title>CatFlex_홈</title>
<h1 class="text-gray-500 text-xs tracking-widest title-font mb-1" _msthash="1093978" _msttexthash="84188" _msthidden="1">Main page</h1>
<section class="text-gray-600 body-font" _msthidden="32">
  <div class="container px-5 py-24 mx-auto" _msthidden="32">
    <div class="flex flex-wrap -m-4" _msthidden="32">
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full" _msthidden="4">
        <a class="block relative h-48 rounded overflow-hidden" _msthidden="1">
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857275" _mstalt="134966">  <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857275" _mstalt="134966">
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857275" _mstalt="134966">
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857275" _mstalt="134966">
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857275" _mstalt="134966">

        </a>
        <div class="mt-4" _msthidden="3">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1" _msthash="1093976" _msttexthash="84188" _msthidden="1">category</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium" _msthash="1093977" _msttexthash="204971" _msthidden="1"> Genre</h2>
        </div>
      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full" _msthidden="4">
        <a class="block relative h-48 rounded overflow-hidden" _msthidden="1">
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857276" _mstalt="134966">
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857276" _mstalt="134966">
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857276" _mstalt="134966">
 <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857276" _mstalt="134966">
             <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857276" _mstalt="134966">
        </a>
        <div class="mt-4" _msthidden="3">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1" _msthash="1093978" _msttexthash="84188" _msthidden="1">CATEGORY</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium" _msthash="1093979" _msttexthash="232921" _msthidden="1">watched movies</h2>

        </div>
      </div>
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full" _msthidden="4">
        <a class="block relative h-48 rounded overflow-hidden" _msthidden="1">
          <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857277" _mstalt="134966">
           <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857277" _mstalt="134966">
  <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857277" _mstalt="134966">
         <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857277" _mstalt="134966">
         <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/260x100" _msthidden="A" _msthiddenattr="857277" _mstalt="134966">

        </a>
        <div class="mt-4" _msthidden="3">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1" _msthash="1093980" _msttexthash="84188" _msthidden="1">category</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium" _msthash="1093981" _msttexthash="96746" _msthidden="1">similar movie</h2>
          <p class="mt-1" _msthash="1049354" _msttexthash="34554" _msthidden="1"></p>
        </div>

        </div>

    </div>
  </div>
</section>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                또는 <a href="{% url 'cat:signup' %}">계정을만드세요</a>
            </span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'cat:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- 로그인 성공 후 이동되는 URL
        <input type="hidden" name="next" value="{{ next }}">


        <div class="form-group"><label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        -->
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'cat:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id">ID</label>
            <input type="text" class="form-control" name="id" id="id" value="{{ form.id.value|default_if_none:'' }}">
        </div>

        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/navbar.html
<!-- 네비게이션 바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="http://localhost:8000/myview/genre/Animation/">Catflex</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if username %}
                <a class="nav-link" href="/myview/logout">{{ username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="/myview/login">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>